name: Node.js Package

on:
  push:
    branches: [master]
  release:
    types: [created]

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Extract Package Version
        id: extract_version
        run: |
          node check-version.js
      - name: publish
        if: steps.extract_version.outputs.should_publish == 1
        run: |
          echo ${{ steps.extract_version.outputs.should_publish }}
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
